name: 'Setup Node & Yarn'
description: 'Sets up Node.js with a specific version and enables Corepack for Yarn'

inputs:
  node-version:
    description: 'Version of Node.js to use'
    required: false
    default: '24.14.0'
  cache:
    description: 'Used to specify a package manager for caching in the default directory'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
