#!/bin/bash

# Exit on error
set -e

JSON_FILE="e2e-matrix.json"
OUTPUT_ENV=".env"

if [ ! -f "$JSON_FILE" ]; then
    echo "Error: $JSON_FILE not found. This script requires a matrix file to resolve tags."
    exit 1
fi

# List of allowed services
ALLOWED_SERVICES=("api-gateway" "ms-user" "ms-event" "ms-social" "ms-post")

# Detect current repository and branch from GitHub environment
CURRENT_SERVICE=""
if [ -n "$GITHUB_REPOSITORY" ]; then
    CURRENT_SERVICE=${GITHUB_REPOSITORY#*/}
fi
CURRENT_BRANCH=${GITHUB_REF_NAME:-"main"}

# Clear or create the .env file
echo "# Generated by e2e-matrix-parsing.sh" > "$OUTPUT_ENV"

# Validate JSON keys using jq
SERVICES_IN_JSON=$(jq -r 'keys[]' "$JSON_FILE")
for SERVICE in $SERVICES_IN_JSON; do
    IS_ALLOWED=false
    for ALLOWED in "${ALLOWED_SERVICES[@]}"; do
        if [ "$SERVICE" == "$ALLOWED" ]; then
            IS_ALLOWED=true
            break
        fi
    done
    if [ "$IS_ALLOWED" = false ]; then
        echo "Error: unknown service '$SERVICE' in $JSON_FILE"
        exit 1
    fi
done

# Function to resolve branch to tag
resolve_tag() {
    local branch=$1
    if [ "$branch" == "main" ]; then
        echo "latest"
    else
        # Replace / with - as buildx/GHA tags usually do
        echo "${branch//\//-}"
    fi
}

# Process each allowed service and generate output
for SERVICE in "${ALLOWED_SERVICES[@]}"; do
    # Try to get branch from JSON
    BRANCH=$(jq -r --arg svc "$SERVICE" '.[$svc] // empty' "$JSON_FILE")
    
    if [ "$SERVICE" == "$CURRENT_SERVICE" ]; then
        # Use current branch for the service being tested
        BRANCH=$CURRENT_BRANCH
    fi

    # Fallback to main if branch is still empty (should not happen if validated)
    if [ -z "$BRANCH" ]; then
        BRANCH="main"
    fi

    TAG=$(resolve_tag "$BRANCH")
    
    # Convert service name to env var format
    ENV_VAR_NAME=$(echo "${SERVICE^^}" | tr '-' '_')_TAG
    
    # Write to .env file
    echo "${ENV_VAR_NAME}=${TAG}" >> "$OUTPUT_ENV"
    
    # Output for GitHub Actions
    if [ -n "$GITHUB_ENV" ]; then
        echo "${ENV_VAR_NAME}=${TAG}" >> "$GITHUB_ENV"
    fi
    
    # Also print to stdout
    echo "${ENV_VAR_NAME}=${TAG}"
done

echo -e "\nSuccessfully generated $OUTPUT_ENV"
