name: Mobile CI (Expo)

on:
  workflow_call:
    secrets:
      EXPO_TOKEN:
        required: false

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node & Yarn
        uses: Volontariapp/ci-tools/.github/actions/setup-node-yarn@main
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn jest

      - name: React Doctor Check
        continue-on-error: true
        run: |
          SCORE=$(yarn doctor . --score | grep -Eo '[0-9]+' | tail -n1)
          echo "React Doctor Score: $SCORE"
          if [ "$SCORE" -lt 95 ]; then
            echo "Score ($SCORE) is below 95! Please fix React Doctor warnings."
            echo "run : yarn doctor ."
            exit 1
          fi

      - name: Type Check
        run: yarn ts:check

      - name: Expo Setup
        run: |
          yarn dlx eas-cli --version
          yarn expo install --check

      - name: Preview Build (Prebuild Check)
        run: npx expo prebuild --no-install
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: EAS Build Dry Run
        run: |
          echo "Verifying EAS configuration..."
          npx expo config --type public
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
