name: Docker Build & Push on GitHub Container Registry

on: 
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps: 
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Check for docker-and-e2e label
        if: github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'docker-and-e2e')
        run: |
          echo "::error::The 'docker-and-e2e' label is missing. If you want the PR to be mergeable, add the tag to run the full CI."
          exit 1

      - name: Build and Push Docker Image (with optional E2E)
        uses: Volontariapp/ci-tools/.github/actions/docker-build-push@main
        with:

          service-name: ${{ inputs.service-name }}
          context: .
          file: ./Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}